### PR TITLE
Update pyproject.toml

### PR DESCRIPTION
**Pull request by AMEERAZAM08**
`pip install 'accelerate>=0.26.0'` require for  Marigold

## 🔘 Description

_No description provided._

## 🔘 Related tasks

**Pull requests**:
- _N/A_

**Issues**:
- _N/A_

## 🔘 Checklist
- [x] I have read the website page about [**Contributing (WIP)**](https://brokensrc.dev/about/contributing) to BrokenSource as of this date

### CODE REVIEW

**Comment by AMEERAZAM08** [comment]
@Tremeschin  Look into this Please

**Comment by Tremeschin** [comment]
This should be handled at runtime here:

https://github.com/BrokenSource/BrokenSource/blob/78bed00d1eb0626b64c9ec5074ced152b16309cf/Broken/Externals/Depthmap.py#L177

I avoid adding dependencies that triggers pytorch/large deps at all costs, because other projects might not depend on it, and torch has different 'flavors' (cuda,cpu,rocm) that the user should make a choice

~

is the version 0.26.0 strictly necessary for marigold? I never really used it for anything, but I remember at least getting it to work, tbh depth anything is just better, is smaller and uses much less vram

**Comment by Tremeschin** [comment]
took a bit to download and ~20 seconds to estimate, seems fine here at least on linux with accelerate 0.34.2

image

**Comment by AMEERAZAM08** [comment]
@Tremeschin  sam updated the file install

**Comment by Tremeschin** [comment]
It's been a while, thanks for the contribution!

Since then I've had at least three users running marigold without any issues with the current approach at runtime, and the _"avoid adding dependencies that triggers pytorch"_ still holds, so I'm sorry this can't be merged, I hope you understand :)

**Pull request closed without merging**
